#!/usr/bin/env python

from __future__ import print_function
import sys
import subprocess
import requests
import getpass
import textwrap
from colorama import init, Fore, Back, Style

init()

try:
    username = subprocess.check_output(['git', 'config', 'github.username'])
    username = username.strip()
except subprocess.CalledProcessError:
    print("No Github username found!")
    print("Please set with:")
    print("\tgit config github.username <username>")
    sys.exit(1)

try:
    repouser = subprocess.check_output(['git', 'config', 'github.repouser'])
    repouser = repouser.strip()
except subprocess.CalledProcessError:
    print("No Github repo username found!")
    print("Please set with:")
    print("\tgit config github.repouser <repo username>")
    sys.exit(1)

try:
    reponame = subprocess.check_output(['git', 'config', 'github.reponame'])
    reponame = reponame.strip()
except subprocess.CalledProcessError:
    print("No Github repo name found!")
    print("Please set with:")
    print("\tgit config github.reponame <repo name>")
    sys.exit(1)

password = getpass.getpass("Please enter password: ")

def parse_event(event):
    event_id = event['id']
    event_type = event['type']
    event_user = event['actor']['login']
    event_userurl = event['actor']['url']
    event_timestamp = event['created_at']

    # Header
    header = u'' + Fore.YELLOW + event_id + u' ' + event_type + Fore.RESET + \
            '\nAuthor: {0} <{1}>'.format(event_user, event_userurl) + \
            '\nDate:   {0}'.format(event_timestamp)
    print(header)

    if event_type == 'PushEvent':
        head_sha = event['payload']['head']
        ref = event['payload']['ref']
        # Find the associated message for HEAD
        message = 'Unknown'
        author = 'Unknown'
        email = 'Unknown'
        for commit in event['payload']['commits']:
            if commit['sha'] == head_sha:
                message = commit['message']
                author = commit['author']['name']
                email = commit['author']['email']

        print(u"SHA:    {0}".format(head_sha) +
              u"\nUser:   {0} <{1}>".format(author, email) +
              u"\nRef:    {0}\n".format(ref))

        if message == 'Unknown':
            print(event.dumps(sort_keys=True, indent=4, separators=(',', ': ')))
        pretty_message = textwrap.wrap(message)
        for l in pretty_message:
            print(l)
        print()
    else:
        # Catch-all for everything else
        print(u"{0} {1} {2}\n".format(event_id, event_type, event_user))

url = "https://api.github.com/repos/{0}/{1}/events".format(repouser, reponame)

r = requests.get(url, auth=(username, password))

events = r.json()

for e in events:
    parse_event(e)

